[build-system]
requires = [
    "setuptools >= 42",
    "setuptools_scm[toml] >= 7.0",
    "wheel >= 0.29.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "animatplot/_version.py"
