name: black

on: push

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Installing black
      run: |
        sudo apt update -y
        sudo apt -y install python3-pip python3-setuptools python3-wheel
        pip3 install black[jupyter]

    - name: Version
      run: |
        python3 --version
        $HOME/.local/bin/black --version

    - name: Run black
      run: |
        $HOME/.local/bin/black . $(grep '^#!.*/bin/.*python.*$' . -Ir|cut -d: -f1)

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply black changes"
